package com.ruoyi.web.controller.stock;
import java.math.*; import java.util.*; import org.springframework.web.bind.annotation.*; import org.springframework.security.access.prepost.PreAuthorize; import com.ruoyi.common.core.controller.BaseController; import com.ruoyi.common.core.domain.AjaxResult; import com.ruoyi.system.domain.stock.*; import com.ruoyi.system.service.*;
@RestController @RequestMapping("/stock/position") public class StockPositionController extends BaseController {
 private final IStockPositionService service; private final IStockAnalyzerService analyzer; private final IStockPositionAnalysisSnapshotService snapshots; public StockPositionController(IStockPositionService s,IStockAnalyzerService a,IStockPositionAnalysisSnapshotService snapshots){service=s;analyzer=a;this.snapshots=snapshots;}
 @PreAuthorize("@ss.hasPermi('stock:position:list')") @GetMapping("/list") public AjaxResult list(){Long userId=getUserId();List<StockPosition> positions=service.list(userId);StockAccount account=service.account(userId);BigDecimal total=account==null?null:account.getTotalAssets();for(StockPosition position:positions){StockAnalysisResult snapshot=snapshots.get(userId,position.getPositionId());position.setPositionPct(service.positionPercent(snapshot==null?null:snapshot.getHolding(),total));}return success(positions);}
 @PreAuthorize("@ss.hasPermi('stock:position:list')") @GetMapping("/account") public AjaxResult account(){return success(service.account(getUserId()));}
 @PreAuthorize("@ss.hasPermi('stock:position:edit')") @PostMapping("/account") public AjaxResult account(@RequestBody StockAccount a){service.saveAccount(getUserId(),a);return success();}
 @PreAuthorize("@ss.hasPermi('stock:position:add')") @PostMapping public AjaxResult add(@RequestBody StockPosition p){service.add(getUserId(),p,getUsername());return success();}
 @PreAuthorize("@ss.hasPermi('stock:position:analyze')") @GetMapping("/{id}/analysis") public AjaxResult latest(@PathVariable Long id){service.get(getUserId(),id);return success(snapshots.get(getUserId(),id));}
 @PreAuthorize("@ss.hasPermi('stock:position:analyze')") @PostMapping("/{id}/analyze") public AjaxResult analyze(@PathVariable Long id,@RequestBody(required=false) Map<String,Boolean> b){boolean includeAi=b!=null&&Boolean.TRUE.equals(b.get("includeAi"));StockPosition p=service.get(getUserId(),id);StockAnalysisResult r=analyzer.analyze(p.getStockCode(),includeAi);r.getIndicators().put("indexTrend",analyzer.analyze("sh000001",false).getTrendDesc());Map<String,Object> h=new HashMap<>();BigDecimal value=BigDecimal.valueOf(r.getStock().getCurrentPrice()).multiply(BigDecimal.valueOf(p.getQuantity()));BigDecimal cost=p.getCostPrice().multiply(BigDecimal.valueOf(p.getQuantity()));h.put("costAmount",cost);h.put("marketValue",value);h.put("profitAmount",value.subtract(cost));h.put("profitPct",value.subtract(cost).multiply(BigDecimal.valueOf(100)).divide(cost,2,RoundingMode.HALF_UP));StockAccount a=service.account(getUserId());h.put("totalAssets",a==null?null:a.getTotalAssets());h.put("positionPct",a==null?null:value.multiply(BigDecimal.valueOf(100)).divide(a.getTotalAssets(),2,RoundingMode.HALF_UP));r.setHolding(h);if(!includeAi){StockAnalysisResult previous=snapshots.get(getUserId(),id);if(previous!=null){r.setAiAdvice(previous.getAiAdvice());r.setAiReason(previous.getAiReason());r.setRiskLevel(previous.getRiskLevel());}}snapshots.save(getUserId(),id,r);return success(r);}
 @PreAuthorize("@ss.hasPermi('stock:position:edit')") @PutMapping public AjaxResult update(@RequestBody StockPosition p){service.update(getUserId(),p,getUsername());return success();}
}
