const fs = require('fs')
const path = require('path')
const assert = require('assert')

const component = fs.readFileSync(path.join(__dirname, '../src/components/StockStrategyReport/index.vue'), 'utf8')
const analyzer = fs.readFileSync(path.join(__dirname, '../src/views/stock/analyzer/index.vue'), 'utf8')
const watchlist = fs.readFileSync(path.join(__dirname, '../src/views/stock/watchlist/index.vue'), 'utf8')
const position = fs.readFileSync(path.join(__dirname, '../src/views/stock/position/index.vue'), 'utf8')

assert.ok(component.indexOf("'data-testid': 'rule-evidence'") < component.indexOf("'data-testid': 'rule-reason'"), 'evidence must precede reason in DOM')
assert.ok(component.includes('v-if="trendIsUp" class="strategy-report__section" data-testid="buy-point-step"'))
assert.ok(component.includes("this.report.trendStep.conclusion === 'UP'"))
assert.ok(component.includes('.strategy-rule__evidence { display: flex; flex-wrap: wrap;'))
assert.ok(component.includes('flex: 1 1 112px;'))
assert.ok(component.includes('max-width: none;'))
assert.ok(component.includes('grid-template-columns: repeat(auto-fit, minmax(230px, 1fr));'))
assert.ok(component.includes('v-if="holdingMode && exitRules.length"'))
assert.ok(component.includes('v-if="holdingMode" class="strategy-report__section" data-testid="position-management-step"'))
assert.ok(analyzer.includes('@ai-analyze="handleAiAnalyze"'))
assert.ok(watchlist.includes('@ai-analyze="handleAiAnalyze(scope.row)"'))
assert.ok(position.includes('holding-mode'))
assert.ok(!analyzer.includes('holding-mode'))
assert.ok(!watchlist.includes('holding-mode'))
assert.ok(component.includes('旧版分析'))
assert.ok(component.indexOf('DeepSeek 综合解读') < component.indexOf('>AI 分析</el-button>'))
assert.ok(component.includes('class="strategy-report__ai-actions"'))

console.log('stock strategy report tests passed')
